- name: Download latest CakePHP
  command: composer create-project --prefer-dist cakephp/app:~4.0 /vagrant/{{ app_dir_name }}
  args:
    creates: "/vagrant/{{ app_dir_name }}"
  notify: Set up CakePHP app config

- name: Install composer dependencies
  command: composer --working-dir=/vagrant/{{ app_dir_name }} install
  args:
    creates: "/vagrant/{{ app_dir_name }}/vendor"
