- name: Install mysql
  apt:
    name: mysql-server
    state: present

- name: Install mysql requisites
  apt:
    name: python3-pymysql
    state: present

- name: Creates mysql database
  mysql_db:
    name: "{{ mysql_database }}"
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create mysql user
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_database }}.*:ALL"
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock