- name: Download and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/vagrant"
    remote_src: yes
    creates: "/vagrant/{{ app_dir_name }}"
  notify: Set up WordPress wp-config
