Vagrant.configure("2") do |config|
    config.vagrant.plugins = ["vagrant-hostsupdater"]
    config.vm.box = "generic/ubuntu2004"
    config.vm.synced_folder "./", "/vagrant"
    config.vm.network :private_network, ip: "192.168.3.10"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.hostsupdater.aliases = [
        "example.local",
        "phpmyadmin.local",
    ]
end
