- name: Import mysql database
  mysql_db:
    name: "{{ mysql_database }}"
    state: import
    target: "{{ mysql_database_import_path }}"
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: mysql_database_need_import
