Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu1804"
    config.vm.synced_folder "./", "/vagrant"
    config.vm.network :private_network, ip: "192.168.3.10"
    config.vm.network "forwarded_port", guest: 8100, host: 8100
    config.vm.provision "ansible_local" do |ansible|
        ansible.install_mode = "pip"
        ansible.playbook = "provision/playbook.yml"
    end
end
